--- #YAML:1.0
name:               Authen-SASL-XS
version:            1.00
abstract:           ~
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Devel::CheckLib:  0
requires:
    Authen::SASL:  2.08
    Test::More:    0
    Test::Simple:  0
resources:
    repository:  http://github.com/gbarr/perl-authen-sasl-xs
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
